# Generated by Django 6.0.1 on 2026-01-09 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('decided_by', models.CharField(max_length=255)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('artifact_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_decision', to='artifacts.artifactversion')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
    ]
